% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{russian}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Анализ данных: Заработная плата и факторы влияния},
  pdfauthor={Peter Tsivinsky / t.me/tsivi\_sky},
  pdflang={ru-RU},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Анализ данных: Заработная плата и факторы влияния}
\author{Peter Tsivinsky / t.me/tsivi\_sky}
\date{2024-12-20}

\begin{document}
\maketitle

\section{1. Введение}\label{ux432ux432ux435ux434ux435ux43dux438ux435}

В этом проекте мы анализируем данные о заработной плате и связанных с
ней факторах, чтобы выявить закономерности и сделать выводы, которые
могут быть полезны для понимания влияния различных характеристик, таких
как опыт работы, уровень образования, должность, а также результаты
экзаменов по математике и программированию на уровень дохода.

Основной задачей является продемонстрировать подходы к обработке и
анализу данных с использованием языка программирования R, включая
визуализацию результатов и выводы.

\section{2. Загрузка библиотек и
данных}\label{ux437ux430ux433ux440ux443ux437ux43aux430-ux431ux438ux431ux43bux438ux43eux442ux435ux43a-ux438-ux434ux430ux43dux43dux44bux445}

\subsection{2.1 Подключение
библиотек}\label{ux43fux43eux434ux43aux43bux44eux447ux435ux43dux438ux435-ux431ux438ux431ux43bux438ux43eux442ux435ux43a}

Для начала подключим необходимые библиотеки. Мы будем использовать
\texttt{tidyverse} для обработки данных и визуализации, а также
\texttt{skimr} для описательной статистики.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Установите пакеты, если они не установлены}
\CommentTok{\# install.packages(c("tidyverse", "skimr", "readr"))}

\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(skimr)}
\end{Highlighting}
\end{Shaded}

\subsection{2.2 Загрузка
данных}\label{ux437ux430ux433ux440ux443ux437ux43aux430-ux434ux430ux43dux43dux44bux445}

Данные находятся в файле \texttt{Salary\_Data.csv}. Мы используем
функцию \texttt{read\_csv} для их загрузки. Для установки рабочей
директории можно было бы воспользоваться \texttt{setwd}, но в таком
варианте мы бы привязывались к структуре директорий на своём текущем
рабочем месте и придётся редактировать проект, чтобы посмотреть его на
другом компьютере. Поэтому лучше загрузить датасет на облачное хранилище
и импортировать данные прямо оттуда.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Путь к файлу данных}
\NormalTok{file\_path }\OtherTok{\textless{}{-}} \StringTok{"https://raw.githubusercontent.com/wowxoxo/r{-}lang\_project/refs/heads/master/data/Salary\_Data.csv"}

\CommentTok{\# Загрузка данных}
\NormalTok{salary\_data }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(file\_path)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 6698 Columns: 8
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (3): Gender, Education Level, Job Title
## dbl (5): Age, Years of Experience, Salary, Math exam score, Programming exam...
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Проверим, что данные успешно загружены}
\FunctionTok{head}\NormalTok{(salary\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##     Age Gender `Education Level` `Job Title`       `Years of Experience` Salary
##   <dbl> <chr>  <chr>             <chr>                             <dbl>  <dbl>
## 1    32 Male   Bachelor's        Software Engineer                     5  90000
## 2    28 Female Master's          Data Analyst                          3  65000
## 3    45 Male   PhD               Senior Manager                       15 150000
## 4    36 Female Bachelor's        Sales Associate                       7  60000
## 5    52 Male   Master's          Director                             20 200000
## 6    29 Male   Bachelor's        Marketing Analyst                     2  55000
## # i 2 more variables: `Math exam score` <dbl>, `Programming exam score` <dbl>
\end{verbatim}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Данные успешно загружены. Таблица содержит такие переменные, как
  \texttt{Age}, \texttt{Salary}, \texttt{Years\ of\ Experience},
  \texttt{Math\ exam\ score}, \texttt{Programming\ exam\ score},
  \texttt{Gender}, \texttt{Education\ Level}, и \texttt{Job\ Title}.
\item
  Первые строки показывают, что данные выглядят корректными и готовы для
  анализа.
\end{enumerate}

\section{3. Первичная проверка
данных}\label{ux43fux435ux440ux432ux438ux447ux43dux430ux44f-ux43fux440ux43eux432ux435ux440ux43aux430-ux434ux430ux43dux43dux44bux445}

На этом этапе мы изучим структуру данных, проверим количество строк и
столбцов, а также выявим потенциальные проблемы, такие как пропуски или
некорректные типы даных.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Структура данных}
\FunctionTok{str}\NormalTok{(salary\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## spc_tbl_ [6,698 x 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ Age                   : num [1:6698] 32 28 45 36 52 29 42 31 26 38 ...
##  $ Gender                : chr [1:6698] "Male" "Female" "Male" "Female" ...
##  $ Education Level       : chr [1:6698] "Bachelor's" "Master's" "PhD" "Bachelor's" ...
##  $ Job Title             : chr [1:6698] "Software Engineer" "Data Analyst" "Senior Manager" "Sales Associate" ...
##  $ Years of Experience   : num [1:6698] 5 3 15 7 20 2 12 4 1 10 ...
##  $ Salary                : num [1:6698] 90000 65000 150000 60000 200000 55000 120000 80000 45000 110000 ...
##  $ Math exam score       : num [1:6698] 49 71 77 69 42 63 86 56 67 39 ...
##  $ Programming exam score: num [1:6698] 45 73 76 84 41 69 88 52 74 45 ...
##  - attr(*, "spec")=
##   .. cols(
##   ..   Age = col_double(),
##   ..   Gender = col_character(),
##   ..   `Education Level` = col_character(),
##   ..   `Job Title` = col_character(),
##   ..   `Years of Experience` = col_double(),
##   ..   Salary = col_double(),
##   ..   `Math exam score` = col_double(),
##   ..   `Programming exam score` = col_double()
##   .. )
##  - attr(*, "problems")=<externalptr>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Количество строк и столбцов}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Количество строк:"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(salary\_data), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Количество строк: 6698
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Количество столбцов:"}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(salary\_data), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Количество столбцов: 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Описательная статистика}
\FunctionTok{skim}\NormalTok{(salary\_data)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule\noalign{}
\endfirsthead
\endhead
\bottomrule\noalign{}
\endlastfoot
Name & salary\_data \\
Number of rows & 6698 \\
Number of columns & 8 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
character & 3 \\
numeric & 5 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.2162}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1351}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1892}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0541}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0541}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0811}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1486}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
empty
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
whitespace
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gender & 0 & 1 & 4 & 6 & 0 & 3 & 0 \\
Education Level & 0 & 1 & 3 & 17 & 0 & 7 & 0 \\
Job Title & 0 & 1 & 3 & 37 & 0 & 191 & 0 \\
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.2233}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0971}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1359}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0971}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0874}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0388}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0583}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0680}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0680}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0680}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0583}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Age & 0 & 1 & 33.62 & 7.62 & 21 & 28 & 32 & 38 & 62 & ▇▇▃▂▁ \\
Years of Experience & 0 & 1 & 8.10 & 6.06 & 0 & 3 & 7 & 12 & 34 &
▇▆▂▁▁ \\
Salary & 0 & 1 & 115329.25 & 52789.79 & 350 & 70000 & 115000 & 160000 &
250000 & ▃▇▇▇▁ \\
Math exam score & 0 & 1 & 65.84 & 13.72 & 3 & 57 & 66 & 76 & 100 &
▁▁▅▇▂ \\
Programming exam score & 0 & 1 & 66.96 & 13.64 & 12 & 58 & 68 & 76 & 100
& ▁▁▆▇▂ \\
\end{longtable}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Типы данных:} Столбцы содержат числовые переменные, такие как
  \texttt{Age}, \texttt{Salary}, и \texttt{Years\ of\ Experience}, а
  также категориальные переменные, включая \texttt{Gender},
  \texttt{Education\ Level}, и \texttt{Job\ Title}. Типы данных
  определены корректно.
\item
  \textbf{Размер данных:} Набор данных включает 6698 строк и 8 столбцов,
  что соответствует требованиям.
\item
  \textbf{Пропуски:} Пропуски отсутствуют, что подтверждает высокое
  качество набора данных.
\item
  \textbf{Распределения:} С помощью \texttt{skim()} видно, что данные
  распределены достаточно широко, особенно для таких переменных, как
  зарплата и опыт работы, что обещает интересные инсайты при дальнейшем
  анализе.
\end{enumerate}

\section{4. Предобработка
данных}\label{ux43fux440ux435ux434ux43eux431ux440ux430ux431ux43eux442ux43aux430-ux434ux430ux43dux43dux44bux445}

\subsection{4.1 Приведение названий колонок к нижнему
регистру}\label{ux43fux440ux438ux432ux435ux434ux435ux43dux438ux435-ux43dux430ux437ux432ux430ux43dux438ux439-ux43aux43eux43bux43eux43dux43eux43a-ux43a-ux43dux438ux436ux43dux435ux43cux443-ux440ux435ux433ux438ux441ux442ux440ux443}

Названия столбцов приводим к единому формату для удобства работы.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Приведение названий к нижнему регистру}
\FunctionTok{names}\NormalTok{(salary\_data) }\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{names}\NormalTok{(salary\_data))}

\CommentTok{\# Проверяем изменения}
\FunctionTok{names}\NormalTok{(salary\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "age"                    "gender"                 "education level"       
## [4] "job title"              "years of experience"    "salary"                
## [7] "math exam score"        "programming exam score"
\end{verbatim}

\subsection{4.2 Преобразование названий
столбцов}\label{ux43fux440ux435ux43eux431ux440ux430ux437ux43eux432ux430ux43dux438ux435-ux43dux430ux437ux432ux430ux43dux438ux439-ux441ux442ux43eux43bux431ux446ux43eux432}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Установим и подключим janitor, если он ещё не установлен}
\CommentTok{\# install.packages("janitor")}
\FunctionTok{library}\NormalTok{(janitor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Преобразование всех имен столбцов к удобному формату}
\NormalTok{salary\_data }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{clean\_names}\NormalTok{()}

\CommentTok{\# Проверим результат}
\FunctionTok{colnames}\NormalTok{(salary\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "age"                    "gender"                 "education_level"       
## [4] "job_title"              "years_of_experience"    "salary"                
## [7] "math_exam_score"        "programming_exam_score"
\end{verbatim}

Комментарии: - Все названия столбцов преобразованы в нижний регистр с
заменой пробелов на подчёркивания (\_). - Например,
\texttt{years\ of\ experience} теперь стало
\texttt{years\_of\_experience}, а \texttt{math\ exam\ score} ---
\texttt{math\_exam\_score}.

\subsection{4.3 Обработка
пропусков}\label{ux43eux431ux440ux430ux431ux43eux442ux43aux430-ux43fux440ux43eux43fux443ux441ux43aux43eux432}

Если в данных есть пропуски, мы их обрабатываем. Например, можно удалить
строки с пропусками или заполнить их средним значением.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Проверка пропусков}
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(salary\_data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    age                 gender        education_level 
##                      0                      0                      0 
##              job_title    years_of_experience                 salary 
##                      0                      0                      0 
##        math_exam_score programming_exam_score 
##                      0                      0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# В данном случае пропусков нет, но если бы они были, можно применить следующий код:}
\CommentTok{\# salary\_data \textless{}{-} salary\_data \%\textgreater{}\% drop\_na()}
\end{Highlighting}
\end{Shaded}

\subsubsection{Комментарии:}\label{ux43aux43eux43cux43cux435ux43dux442ux430ux440ux438ux438}

Пропуски в данных отсутствуют, поэтому дополнительная обработка не
требуется.

\section{5. Фильтрация
данных}\label{ux444ux438ux43bux44cux442ux440ux430ux446ux438ux44f-ux434ux430ux43dux43dux44bux445}

Например, мы можем оставить только записи, где \texttt{salary} выше
определённого порога.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Пример фильтрации данных}
\NormalTok{example\_filtered\_data }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(salary }\SpecialCharTok{\textgreater{}} \DecValTok{50000}\NormalTok{)}

\CommentTok{\# Проверим результат фильтрации}
\FunctionTok{nrow}\NormalTok{(example\_filtered\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5827
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# это просто пример, будем работать с полным датасетом, без фильтрации}
\end{Highlighting}
\end{Shaded}

\section{6. Описательная
статистика}\label{ux43eux43fux438ux441ux430ux442ux435ux43bux44cux43dux430ux44f-ux441ux442ux430ux442ux438ux441ux442ux438ux43aux430}

\subsection{6.1 Описательные статистики для числовых
переменных}\label{ux43eux43fux438ux441ux430ux442ux435ux43bux44cux43dux44bux435-ux441ux442ux430ux442ux438ux441ux442ux438ux43aux438-ux434ux43bux44f-ux447ux438ux441ux43bux43eux432ux44bux445-ux43fux435ux440ux435ux43cux435ux43dux43dux44bux445}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Описательные статистики для числовых переменных}
\FunctionTok{summary}\NormalTok{(}\FunctionTok{select}\NormalTok{(salary\_data, age, years\_of\_experience, salary, math\_exam\_score, programming\_exam\_score))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age        years_of_experience     salary       math_exam_score 
##  Min.   :21.00   Min.   : 0.000      Min.   :   350   Min.   :  3.00  
##  1st Qu.:28.00   1st Qu.: 3.000      1st Qu.: 70000   1st Qu.: 57.00  
##  Median :32.00   Median : 7.000      Median :115000   Median : 66.00  
##  Mean   :33.62   Mean   : 8.095      Mean   :115329   Mean   : 65.84  
##  3rd Qu.:38.00   3rd Qu.:12.000      3rd Qu.:160000   3rd Qu.: 76.00  
##  Max.   :62.00   Max.   :34.000      Max.   :250000   Max.   :100.00  
##  programming_exam_score
##  Min.   : 12.00        
##  1st Qu.: 58.00        
##  Median : 68.00        
##  Mean   : 66.96        
##  3rd Qu.: 76.00        
##  Max.   :100.00
\end{verbatim}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-2}

\begin{itemize}
\tightlist
\item
  \texttt{Age}: Средний возраст --- 33.6 лет, диапазон значений --- от
  21 до 62.
\item
  \texttt{Years\ of\ Experience}: Средний опыт --- 8.1 лет, с разбросом
  от 1 до 34.
\item
  \texttt{Salary}: Средняя зарплата составляет 115,329, с диапазоном от
  20,000 до 250,000.
\item
  \texttt{Math\ exam\ score} и \texttt{Programming\ exam\ score}
  распределены схожим образом, с близкими средними значениями (65.8 и
  67.0) и небольшими разбросами.
\end{itemize}

\subsection{6.2 Частоты для категориальных
переменных}\label{ux447ux430ux441ux442ux43eux442ux44b-ux434ux43bux44f-ux43aux430ux442ux435ux433ux43eux440ux438ux430ux43bux44cux43dux44bux445-ux43fux435ux440ux435ux43cux435ux43dux43dux44bux445}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Gender:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Gender:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{gender))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Female   Male  Other 
##   3013   3671     14
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Education Level:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Education Level:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{education\_level))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        Bachelor's Bachelor's Degree       High School          Master's 
##               756              2265               448               288 
##   Master's Degree               phD               PhD 
##              1572                 1              1368
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Job Title:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Job Title:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(job\_title))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 191 x 2
##    job_title                         n
##    <chr>                         <int>
##  1 Account Manager                   1
##  2 Accountant                        1
##  3 Administrative Assistant          2
##  4 Back end Developer              244
##  5 Business Analyst                  2
##  6 Business Development Manager      1
##  7 Business Intelligence Analyst     1
##  8 CEO                               1
##  9 Chief Data Officer                1
## 10 Chief Technology Officer          1
## # i 181 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Job Title (Top 10):}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Job Title (Top 10):
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{head}\NormalTok{(}\FunctionTok{sort}\NormalTok{(}\FunctionTok{table}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{job\_title), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{), }\DecValTok{10}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         Software Engineer            Data Scientist Software Engineer Manager 
##                       518                       453                       376 
##              Data Analyst   Senior Project Engineer           Product Manager 
##                       363                       318                       313 
##       Full Stack Engineer         Marketing Manager        Back end Developer 
##                       308                       255                       244 
##  Senior Software Engineer 
##                       244
\end{verbatim}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-3}

\begin{itemize}
\tightlist
\item
  \texttt{Gender} содержит 6 уникальных значений.
\item
  \texttt{Education\ Level} имеет 7 уникальных категорий.
\item
  \texttt{Job\ Title} включает 191 уникальное значение, что указывает на
  большое разнообразие должностей.
\end{itemize}

\subsection{6.3 Анализ поля
gender}\label{ux430ux43dux430ux43bux438ux437-ux43fux43eux43bux44f-gender}

В данных присутствует 3 уникальных значения в поле gender. Это может
указывать на некорректные данные или опечатки. Давайте изучим их
подробнее.

\subsubsection{Проверка уникальных
значений}\label{ux43fux440ux43eux432ux435ux440ux43aux430-ux443ux43dux438ux43aux430ux43bux44cux43dux44bux445-ux437ux43dux430ux447ux435ux43dux438ux439}

Используем функцию \texttt{unique()} для вывода всех уникальных значений
поля gender.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{gender)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Male"   "Female" "Other"
\end{verbatim}

Видим значение Other, скорее всего кто-то не указал пол при проведении
исследований. Проверим насколько их много, чтобы оценить влияние на
датасет

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Частоты значений в поле gender}
\FunctionTok{table}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{gender)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Female   Male  Other 
##   3013   3671     14
\end{verbatim}

Всего 14 значений, совсем мало по сравнению с остальными. Можно было бы
удалить строки с этимм значениями, но не будем.

\subsection{6.4 Визуализация распределения
gender}\label{ux432ux438ux437ux443ux430ux43bux438ux437ux430ux446ux438ux44f-ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux44f-gender}

Построим круговую диаграмму для переменной gender, чтобы наглядно
представить её распределение.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Создаём таблицу с подсчётом частот}
\NormalTok{gender\_counts }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(gender)}

\CommentTok{\# Построение круговой диаграммы}
\FunctionTok{ggplot}\NormalTok{(gender\_counts, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =}\NormalTok{ n, }\AttributeTok{fill =}\NormalTok{ gender)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{width =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{, }\AttributeTok{start =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_void}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Распределение по полу"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"Gender"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%"}\NormalTok{)), }
            \AttributeTok{position =} \FunctionTok{position\_stack}\NormalTok{(}\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/gender pie-1.pdf}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-4}

\begin{itemize}
\tightlist
\item
  \texttt{Male}: Составляют 54.8\% выборки --- это наиболее
  распространённое значение в поле gender.
\item
  \texttt{Female}: Представляют 45\% данных, что немного меньше по
  сравнению с Male.
\item
  \texttt{Other}: Составляют всего 0.2\% выборки. Эта категория,
  вероятно, связана с некорректным вводом данных или редкими случаями.
\end{itemize}

Данное распределение показывает, что мужчины и женщины представлены
почти равномерно.

\subsection{6.5 Анализ поля
education\_level}\label{ux430ux43dux430ux43bux438ux437-ux43fux43eux43bux44f-education_level}

Теперь мы рассмотрим поле \texttt{education\_level}, чтобы понять его
распределение и возможные особенности. Сначала выведем уникальные
значения и построим таблицу частот.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{education\_level)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Bachelor's"        "Master's"          "PhD"              
## [4] "Bachelor's Degree" "Master's Degree"   "High School"      
## [7] "phD"
\end{verbatim}

Некоторые значения очень похожи, отобразим их на графике, что увидеть
более явно:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Создаём таблицу с подсчётом частот}
\NormalTok{education\_counts }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(education\_level)}

\CommentTok{\# Построение круговой диаграммы}
\FunctionTok{ggplot}\NormalTok{(education\_counts, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =}\NormalTok{ n, }\AttributeTok{fill =}\NormalTok{ education\_level)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{width =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{, }\AttributeTok{start =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_void}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Распределение по уровню образования"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"Education level"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%"}\NormalTok{)), }
            \AttributeTok{position =} \FunctionTok{position\_stack}\NormalTok{(}\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/education pie-1.pdf}

Хорошо, теперь проблема очевидна. Один и тот же уровень образования
называется по-разному. Значения должны быть санитизированы.

\subsection{7. Стандартизация колонки
education\_level}\label{ux441ux442ux430ux43dux434ux430ux440ux442ux438ux437ux430ux446ux438ux44f-ux43aux43eux43bux43eux43dux43aux438-education_level}

Создадим явный маппинг для всех значений и приведём их к нужному
формату:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Явное сопоставление значений}
\NormalTok{salary\_data }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{education\_level =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"Bachelor\textquotesingle{}s Degree"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Bachelor\textquotesingle{}s"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"Bachelor\textquotesingle{}s"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Bachelor\textquotesingle{}s"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"Master\textquotesingle{}s Degree"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Master\textquotesingle{}s"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"Master\textquotesingle{}s"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Master\textquotesingle{}s"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"PhD"} \SpecialCharTok{\textasciitilde{}} \StringTok{"PhD"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"phD"} \SpecialCharTok{\textasciitilde{}} \StringTok{"PhD"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{==} \StringTok{"High School"} \SpecialCharTok{\textasciitilde{}} \StringTok{"High School"}\NormalTok{,}
    \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}}\NormalTok{ education\_level }\CommentTok{\# Для любых других значений}
\NormalTok{  ))}

\CommentTok{\# Проверка результата}
\FunctionTok{table}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{education\_level)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bachelor's High School    Master's         PhD 
##        3021         448        1860        1369
\end{verbatim}

\subsubsection{Комментарии:}\label{ux43aux43eux43cux43cux435ux43dux442ux430ux440ux438ux438-1}

\begin{itemize}
\tightlist
\item
  Значения в \texttt{education\_level} теперь приведены к стандартным
  категориям:

  \begin{itemize}
  \tightlist
  \item
    \texttt{Bachelor\textquotesingle{}s}
  \item
    \texttt{Master\textquotesingle{}s}
  \item
    \texttt{PhD}
  \item
    \texttt{High\ School}
  \end{itemize}
\item
  Явное сопоставление устранило дублирующиеся и некорректные значения
  (например, \texttt{phD} → \texttt{PhD}).
\end{itemize}

\subsection{7.1 Распределение уровня
образования}\label{ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux435-ux443ux440ux43eux432ux43dux44f-ux43eux431ux440ux430ux437ux43eux432ux430ux43dux438ux44f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Создаём таблицу с подсчётом частот}
\NormalTok{education\_counts2 }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(education\_level)}

\CommentTok{\# Построение круговой диаграммы}
\FunctionTok{ggplot}\NormalTok{(education\_counts2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =}\NormalTok{ n, }\AttributeTok{fill =}\NormalTok{ education\_level)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{width =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{, }\AttributeTok{start =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_void}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Распределение по уровню образования"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"Education level"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%"}\NormalTok{)), }
            \AttributeTok{position =} \FunctionTok{position\_stack}\NormalTok{(}\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/education pie 2-1.pdf}

Данные показывают, что большинство людей имеют степень бакалавра или
магистра, а уровень образования \texttt{PhD} также заметно
распространён. Минимальное количество людей с \texttt{High\ School}
указывает на то, что более высокие уровни образования являются нормой
для рассматриваемых должностей.

\subsection{\texorpdfstring{8. Анализ \texttt{job\_title}: роли с
префиксом
\texttt{Junior}}{8. Анализ job\_title: роли с префиксом Junior}}\label{ux430ux43dux430ux43bux438ux437-job_title-ux440ux43eux43bux438-ux441-ux43fux440ux435ux444ux438ux43aux441ux43eux43c-junior}

Поле \texttt{job\_title} содержит множество уникальных значений. Для
интереса исследуем, сколько позиций имеют префикс \texttt{Junior} и
составляют ли они значительную долю среди всех должностей.

\subsubsection{8.1 Проверка случайной выборки
должностей}\label{ux43fux440ux43eux432ux435ux440ux43aux430-ux441ux43bux443ux447ux430ux439ux43dux43eux439-ux432ux44bux431ux43eux440ux43aux438-ux434ux43eux43bux436ux43dux43eux441ux442ux435ux439}

Выведем случайную выборку из \texttt{job\_title}, чтобы оценить данные:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Случайная выборка 5 должностей}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)  }\CommentTok{\# Для воспроизводимости}
\FunctionTok{sample\_n}\NormalTok{(}\FunctionTok{distinct}\NormalTok{(salary\_data, job\_title), }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 1
##    job_title                        
##    <chr>                            
##  1 Senior IT Consultant             
##  2 Front end Developer              
##  3 Project Manager                  
##  4 Junior Operations Coordinator    
##  5 Business Intelligence Analyst    
##  6 Junior Project Manager           
##  7 Administrative Assistant         
##  8 Marketing Director               
##  9 Juniour HR Coordinator           
## 10 Senior Human Resources Specialist
\end{verbatim}

\subsubsection{\texorpdfstring{8.2 Позиции с префиксом
\texttt{Junior}}{8.2 Позиции с префиксом Junior}}\label{ux43fux43eux437ux438ux446ux438ux438-ux441-ux43fux440ux435ux444ux438ux43aux441ux43eux43c-junior}

Фильтрация должностей с \texttt{Junior}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Фильтрация должностей с "Junior"}
\NormalTok{junior\_job\_titles }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{str\_detect}\NormalTok{(job\_title, }\FunctionTok{regex}\NormalTok{(}\StringTok{"Junior"}\NormalTok{, }\AttributeTok{ignore\_case =} \ConstantTok{TRUE}\NormalTok{)))}

\CommentTok{\# Количество должностей с "Junior"}
\NormalTok{junior\_job\_title\_counts }\OtherTok{\textless{}{-}}\NormalTok{ junior\_job\_titles }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(job\_title, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Просмотр результата}
\NormalTok{junior\_job\_title\_counts}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 36 x 2
##    job_title                       n
##    <chr>                       <int>
##  1 Junior Sales Associate        142
##  2 Junior HR Generalist           60
##  3 Junior Software Developer      58
##  4 Junior Marketing Manager       51
##  5 Junior Software Engineer       51
##  6 Junior Web Developer           42
##  7 Junior Sales Representative    41
##  8 Junior HR Coordinator          29
##  9 Junior Data Analyst            25
## 10 Junior Business Analyst         8
## # i 26 more rows
\end{verbatim}

\subsubsection{\texorpdfstring{8.3 Общее число позиций с
\texttt{Junior}}{8.3 Общее число позиций с Junior}}\label{ux43eux431ux449ux435ux435-ux447ux438ux441ux43bux43e-ux43fux43eux437ux438ux446ux438ux439-ux441-junior}

Подсчёт общего числа позиций с \texttt{Junior}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Подсчёт общего числа позиций с "Junior"}
\NormalTok{total\_junior\_jobs }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(junior\_job\_titles)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Total number of job titles containing \textquotesingle{}Junior\textquotesingle{}:"}\NormalTok{, total\_junior\_jobs, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Total number of job titles containing 'Junior': 573
\end{verbatim}

\subsubsection{\texorpdfstring{8.4 Процент позиций с
\texttt{Junior}}{8.4 Процент позиций с Junior}}\label{ux43fux440ux43eux446ux435ux43dux442-ux43fux43eux437ux438ux446ux438ux439-ux441-junior}

Расчёт процента позиций с \texttt{Junior}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Общее число должностей}
\NormalTok{total\_jobs }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(salary\_data)}

\CommentTok{\# Расчёт процента должностей с "Junior"}
\NormalTok{percent\_junior\_jobs }\OtherTok{\textless{}{-}}\NormalTok{ (total\_junior\_jobs }\SpecialCharTok{/}\NormalTok{ total\_jobs) }\SpecialCharTok{*} \DecValTok{100}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Percentage of \textquotesingle{}Junior\textquotesingle{} job titles:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(percent\_junior\_jobs, }\DecValTok{2}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Percentage of 'Junior' job titles: 8.55 %
\end{verbatim}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-5}

Примерно 8\% всех позиций в наборе данных относятся к начальному или
раннему уровню карьеры.

Это говорит о том, что выборка больше ориентирована на должности
среднего и старшего уровня, но включает достаточное количество начальных
позиций.

Выборка с Junior подтверждает наличие разнообразных должностей,
подходящих для начинающих специалистов.

\section{9. Визуализация и
исследование}\label{ux432ux438ux437ux443ux430ux43bux438ux437ux430ux446ux438ux44f-ux438-ux438ux441ux441ux43bux435ux434ux43eux432ux430ux43dux438ux435}

Мы уже создали несколько визуализаций. Теперь рассмотрим распределение
зарплат и вычислим центральные тенденции и разброс.

\subsection{9.1 Распределение
зарплат}\label{ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux435-ux437ux430ux440ux43fux43bux430ux442}

Центральные тенденции и разброс

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Вычисление среднего, медианы и стандартного отклонения для зарплат}
\NormalTok{salary\_mean }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{salary\_median }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{salary\_std }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Вывод результатов}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean Salary:"}\NormalTok{, salary\_mean, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean Salary: 115329.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Median Salary:"}\NormalTok{, salary\_median, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Median Salary: 115000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Standard Deviation of Salary:"}\NormalTok{, salary\_std, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Standard Deviation of Salary: 52789.79
\end{verbatim}

\subsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-6}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Средняя зарплата (Mean Salary): 115,329.25. Это среднее значение
  зарплат в наборе данных.
\item
  Медианная зарплата (Median Salary): 115,000. Значение медианы близко к
  среднему, что указывает на относительно сбалансированное распределение
  зарплат.
\item
  Стандартное отклонение (Standard Deviation): 52,789.79. Высокое
  значение стандартного отклонения показывает широкий диапазон зарплат и
  значительные различия между ними.
\end{enumerate}

\section{9.1.1 Гистограмма распределения
зарплат}\label{ux433ux438ux441ux442ux43eux433ux440ux430ux43cux43cux430-ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux44f-ux437ux430ux440ux43fux43bux430ux442}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение гистограммы распределения зарплат}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{20}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Распределение зарплат"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Зарплата"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Частота"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/salary dist hist-1.pdf}

Странные подписи у оси X, попробуем это исправить с пакетом scales():

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Установите пакет scales, если он не установлен}
\CommentTok{\# install.packages("scales")}
\FunctionTok{library}\NormalTok{(scales)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'scales'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     discard
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:readr':
## 
##     col_factor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение гистограммы с отформатированной осью X}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{20}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}
    \AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\FunctionTok{label\_comma}\NormalTok{(),  }\CommentTok{\# Форматирование в виде чисел с запятыми}
    \AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{max}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{by =} \DecValTok{50000}\NormalTok{) }\CommentTok{\# Шаг 50,000}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Распределение зарплат"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Зарплата"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Частота"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/salary dist hist fixed x-1.pdf}

Отлично, так намного нагляднее.

\subsection{Наблюдения из
визуализации:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-ux438ux437-ux432ux438ux437ux443ux430ux43bux438ux437ux430ux446ux438ux438}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Зарплаты в основном сконцентрированы в диапазоне от 50,000 до 200,000,
  с меньшим количеством людей, получающих очень низкие или очень высокие
  зарплаты.
\item
  Наличие высоких зарплат (до 250,000) указывает на то, что в наборе
  данных представлены роли старшего уровня или специализированные
  позиции, которые получают значительно больше.
\end{enumerate}

\subsection{9.2 Salary vs Years of
Experience}\label{salary-vs-years-of-experience}

Построим диаграмму рассеяния (scatter plot), чтобы визуализировать связь
между опытом работы (\texttt{years\_of\_experience}) и зарплатой
(\texttt{salary}).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение scatter plot}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ years\_of\_experience, }\AttributeTok{y =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Опыт работы vs Зарплата"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Опыт работы (лет)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/salary vs exp-1.pdf}

\subsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-7}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Положительная корреляция: На диаграмме видно, что зарплата, как
  правило, увеличивается с ростом опыта работы. Это подтверждает
  гипотезу о том, что опыт играет важную роль в определении зарплаты.
\item
  Неидеальная линейность:

  \begin{itemize}
  \tightlist
  \item
    Есть аутлайеры: люди с высокой зарплатой, несмотря на небольшой опыт
    работы.
  \item
    Также есть люди с низкой зарплатой, несмотря на значительный опыт.
  \end{itemize}
\item
  Вариация зарплат: На всех уровнях опыта заметен разброс зарплат, что
  указывает на влияние других факторов, таких как должность, уровень
  образования или отрасль.
\end{enumerate}

\subsection{9.3 Education и Salary}\label{education-ux438-salary}

Построим boxplot, чтобы изучить распределение зарплат для каждой
категории уровня образования (\texttt{education\_level}). Это поможет
визуализировать медиану, межквартильный размах и выбросы для каждой
группы.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение boxplot}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education\_level, }\AttributeTok{y =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{outlier.color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{outlier.shape =} \DecValTok{16}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Распределение зарплат по уровню образования"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Уровень образования"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/edu vs salary-1.pdf}

\subsubsection{Интерпретация:}\label{ux438ux43dux442ux435ux440ux43fux440ux435ux442ux430ux446ux438ux44f}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \texttt{PhD}: Обладатели степени \texttt{PhD} имеют самую высокую
  медианную зарплату, что подтверждает, что этот уровень образования
  связан с более высокими доходами.
\item
  \texttt{Master\textquotesingle{}s\ Degree}: Люди с магистерской
  степенью также имеют высокие зарплаты, хотя их диапазон несколько
  шире, чем у \texttt{PhD}.
\item
  \texttt{Bachelor\textquotesingle{}s\ Degree}: Медианная зарплата ниже,
  чем у обладателей продвинутых степеней, но диапазон показывает, что
  многие бакалавры зарабатывают на уровне магистров.
\item
  \texttt{High\ School}: Выпускники средней школы имеют самую низкую
  медианную зарплату и ограниченный диапазон, что говорит о меньших
  возможностях для высоких доходов.
\end{enumerate}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-8}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Зарплата, как правило, увеличивается с ростом уровня образования:
  обладатели степеней \texttt{PhD} и \texttt{Master\textquotesingle{}s}
  получают больше, чем \texttt{Bachelor\textquotesingle{}s} или
  выпускники средней школы.
\item
  Несмотря на тренд, есть значительное пересечение в распределении
  зарплат. Некоторые обладатели \texttt{Bachelor\textquotesingle{}s}
  получают столько же, сколько магистры .
\item
  Широкий диапазон зарплат для всех уровней образования показывает, что
  помимо образования на зарплату влияют такие факторы, как опыт и
  должность.
\end{enumerate}

\subsection{9.4 Распределение
возраста}\label{ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux435-ux432ux43eux437ux440ux430ux441ux442ux430}

В этом разделе мы вычислим центральные тенденции и разброс возраста
(\texttt{age}) и визуализируем его распределение.

\subsubsection{Центральные тенденции и
разброс}\label{ux446ux435ux43dux442ux440ux430ux43bux44cux43dux44bux435-ux442ux435ux43dux434ux435ux43dux446ux438ux438-ux438-ux440ux430ux437ux431ux440ux43eux441}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Вычисление среднего, медианы и стандартного отклонения для возраста}
\NormalTok{age\_mean }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{age, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{age\_median }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{age, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{age\_std }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{age, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Вывод результатов}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean Age:"}\NormalTok{, age\_mean, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean Age: 33.62302
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Median Age:"}\NormalTok{, age\_median, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Median Age: 32
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Standard Deviation of Age:"}\NormalTok{, age\_std, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Standard Deviation of Age: 7.615784
\end{verbatim}

\subsubsection{Построение гистограммы распределения
возраста}\label{ux43fux43eux441ux442ux440ux43eux435ux43dux438ux435-ux433ux438ux441ux442ux43eux433ux440ux430ux43cux43cux44b-ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux44f-ux432ux43eux437ux440ux430ux441ux442ux430}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение гистограммы распределения возраста}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{20}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightgreen"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Распределение возраста"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Возраст"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Частота"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/age dist hist-1.pdf}

\paragraph{Интерпретация:}\label{ux438ux43dux442ux435ux440ux43fux440ux435ux442ux430ux446ux438ux44f-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Центральные тенденции:

  \begin{itemize}
  \tightlist
  \item
    Средний возраст --- 33.6 лет.
  \item
    Медианный возраст --- 32 года.
  \item
    Поскольку среднее и медиана близки, распределение выглядит
    относительно симметричным.
  \end{itemize}
\item
  Разброс: Стандартное отклонение составляет 7.62, что говорит о
  умеренном разбросе возрастов в выборке.
\item
  Распределение: Большинство людей находятся в возрасте от 20 до 40 лет,
  что отражает рабочую популяцию, находящуюся в середине своей карьеры.
  Меньше людей представлено в возрастных группах старше 50 или младше 25
  лет.
\end{enumerate}

\section{10. Более глубокое исследование и вопросы для
анализа}\label{ux431ux43eux43bux435ux435-ux433ux43bux443ux431ux43eux43aux43eux435-ux438ux441ux441ux43bux435ux434ux43eux432ux430ux43dux438ux435-ux438-ux432ux43eux43fux440ux43eux441ux44b-ux434ux43bux44f-ux430ux43dux430ux43bux438ux437ux430}

\subsection{10.1 Распределение мужчин и женщин на разных
должностях}\label{ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux435-ux43cux443ux436ux447ux438ux43d-ux438-ux436ux435ux43dux449ux438ux43d-ux43dux430-ux440ux430ux437ux43dux44bux445-ux434ux43eux43bux436ux43dux43eux441ux442ux44fux445}

\subsubsection{Шаг 1: Топ-5 самых популярных
должностей}\label{ux448ux430ux433-1-ux442ux43eux43f-5-ux441ux430ux43cux44bux445-ux43fux43eux43fux443ux43bux44fux440ux43dux44bux445-ux434ux43eux43bux436ux43dux43eux441ux442ux435ux439}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Топ{-}5 самых популярных должностей}
\NormalTok{top\_5\_job\_titles }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(job\_title, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{top\_n}\NormalTok{(}\DecValTok{5}\NormalTok{, n)}

\CommentTok{\# Выводим результат}
\NormalTok{top\_5\_job\_titles}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 2
##   job_title                     n
##   <chr>                     <int>
## 1 Software Engineer           518
## 2 Data Scientist              453
## 3 Software Engineer Manager   376
## 4 Data Analyst                363
## 5 Senior Project Engineer     318
\end{verbatim}

\subsubsection{Шаг 2: Распределение по полу для топ-5
должностей}\label{ux448ux430ux433-2-ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux435-ux43fux43e-ux43fux43eux43bux443-ux434ux43bux44f-ux442ux43eux43f-5-ux434ux43eux43bux436ux43dux43eux441ux442ux435ux439}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Фильтрация данных для топ{-}5 должностей и подсчёт распределения по полу}
\NormalTok{gender\_job\_distribution }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(job\_title }\SpecialCharTok{\%in\%}\NormalTok{ top\_5\_job\_titles}\SpecialCharTok{$}\NormalTok{job\_title) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(job\_title, gender) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ gender, }\AttributeTok{values\_from =}\NormalTok{ n, }\AttributeTok{values\_fill =} \DecValTok{0}\NormalTok{)}

\CommentTok{\# Выводим результат}
\NormalTok{gender\_job\_distribution}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 4
##   job_title                 Female  Male Other
##   <chr>                      <int> <int> <int>
## 1 Data Analyst                 129   234     0
## 2 Data Scientist               202   251     0
## 3 Senior Project Engineer      103   213     2
## 4 Software Engineer            193   325     0
## 5 Software Engineer Manager    100   276     0
\end{verbatim}

\subsubsection{Шаг 3: Визуализация распределения (Stacked Bar
Chart)}\label{ux448ux430ux433-3-ux432ux438ux437ux443ux430ux43bux438ux437ux430ux446ux438ux44f-ux440ux430ux441ux43fux440ux435ux434ux435ux43bux435ux43dux438ux44f-stacked-bar-chart}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение stacked bar chart для распределения по полу}
\FunctionTok{ggplot}\NormalTok{(gender\_job\_distribution, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ job\_title)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Male, }\AttributeTok{fill =} \StringTok{"Male"}\NormalTok{), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Female, }\AttributeTok{fill =} \StringTok{"Female"}\NormalTok{), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Male"} \OtherTok{=} \StringTok{"lightblue"}\NormalTok{, }\StringTok{"Female"} \OtherTok{=} \StringTok{"pink"}\NormalTok{), }\AttributeTok{name =} \StringTok{"Gender"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Распределение мужчин и женщин в топ{-}5 должностей"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Должность"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Количество сотрудников"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/job/gender stacked bar-1.pdf}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-9}

Гендерный дисбаланс наблюдается в технических и инженерных ролях, таких
как \texttt{Software\ Engineer\ Manager}, с преобладанием мужчин. Для
позиции \texttt{Data\ Scientist} видно преобладание женщин. Другие роли
демонстрируют более равное представительство.

\subsection{10.2 Влияет ли опыт на
зарплату?}\label{ux432ux43bux438ux44fux435ux442-ux43bux438-ux43eux43fux44bux442-ux43dux430-ux437ux430ux440ux43fux43bux430ux442ux443}

Для проверки влияния опыта работы (\texttt{years\_of\_experience}) на
зарплату (\texttt{salary}), построим диаграмму рассеяния и вычислим
корреляцию между этими переменными.

\subsubsection{Построение диаграммы
рассеяния}\label{ux43fux43eux441ux442ux440ux43eux435ux43dux438ux435-ux434ux438ux430ux433ux440ux430ux43cux43cux44b-ux440ux430ux441ux441ux435ux44fux43dux438ux44f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение scatter plot}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ years\_of\_experience, }\AttributeTok{y =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Опыт работы vs Зарплата"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Опыт работы (лет)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/exp/sal plot-1.pdf}

\subsubsection{Вычисление
корреляции}\label{ux432ux44bux447ux438ux441ux43bux435ux43dux438ux435-ux43aux43eux440ux440ux435ux43bux44fux446ux438ux438}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Вычисление корреляции между опытом работы и зарплатой}
\NormalTok{experience\_salary\_corr }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{years\_of\_experience, salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}

\CommentTok{\# Вывод результата}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation between experience and salary:"}\NormalTok{, experience\_salary\_corr, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation between experience and salary: 0.8089682
\end{verbatim}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-10}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Чёткая положительная связь: График подтверждает, что с ростом опыта
  работы зарплата, как правило, увеличивается. Основная масса данных
  соответствует ожидаемой тенденции.
\item
  Разброс данных: На низком уровне опыта (0--10 лет) зарплаты
  варьируются в широком диапазоне от 20,000 до 150,000, что указывает на
  влияние других факторов, таких как должность или образование. Для
  среднего опыта (10--20 лет) распределение становится более
  концентрированным, но всё же присутствуют выбросы.
\item
  Насыщенность данных: В верхнем диапазоне опыта (20+ лет) зарплаты
  имеют меньше вариаций, концентрируясь около 150,000--200,000. Однако
  встречаются аномалии, где люди с большим опытом имеют зарплаты ниже
  ожидаемого уровня.
\item
  Корреляция: Корреляция 0.81 подтверждает, что опыт работы является
  важным фактором, влияющим на зарплату. Несмотря на сильную связь,
  присутствие выбросов показывает, что другие факторы, такие как
  отрасль, регион или тип компании, также оказывают значительное
  влияние.
\end{enumerate}

\subsection{10.3 Влияют ли результаты экзаменов по математике и
программированию на
зарплату?}\label{ux432ux43bux438ux44fux44eux442-ux43bux438-ux440ux435ux437ux443ux43bux44cux442ux430ux442ux44b-ux44dux43aux437ux430ux43cux435ux43dux43eux432-ux43fux43e-ux43cux430ux442ux435ux43cux430ux442ux438ux43aux435-ux438-ux43fux440ux43eux433ux440ux430ux43cux43cux438ux440ux43eux432ux430ux43dux438ux44e-ux43dux430-ux437ux430ux440ux43fux43bux430ux442ux443}

Мы проверим, есть ли связь между результатами экзаменов по математике и
программированию (\texttt{math\_exam\_score},
\texttt{programming\_exam\_score}) и зарплатой (\texttt{salary}).

\subsubsection{\texorpdfstring{10.3.1 \texttt{Math\ Exam\ Score}
vs.~\texttt{Salary}}{10.3.1 Math Exam Score vs.~Salary}}\label{math-exam-score-vs.-salary}

Построение диаграммы рассеяния

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Диаграмма рассеяния для Math Exam Score vs Salary}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ math\_exam\_score, }\AttributeTok{y =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Результат экзамена по математике vs Зарплата"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Результат экзамена по математике"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/math exam vs salary dist-1.pdf}

Корреляция между математикой и зарплатой

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Вычисление корреляции между Math Exam Score и Salary}
\NormalTok{math\_salary\_corr }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{math\_exam\_score, salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}

\CommentTok{\# Вывод результата}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation between Math exam score and Salary:"}\NormalTok{, math\_salary\_corr, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation between Math exam score and Salary: 0.02338351
\end{verbatim}

\paragraph{\texorpdfstring{Наблюдения \texttt{Math\ Exam\ Score}
vs.~\texttt{Salary}:}{Наблюдения Math Exam Score vs.~Salary:}}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-math-exam-score-vs.-salary}

Диаграмма рассеяния показывает отсутствие явной тенденции (восходящей
или нисходящей), что указывает на слабую связь между результатами
экзаменов по математике и зарплатой. Коэффициент корреляции составляет
0.02, что близко к нулю и подтверждает отсутствие значимой зависимости.

\subsubsection{\texorpdfstring{10.3.2 \texttt{Programming\ Exam\ Score}
vs.~\texttt{Salary}}{10.3.2 Programming Exam Score vs.~Salary}}\label{programming-exam-score-vs.-salary}

Построение диаграммы рассеяния

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Диаграмма рассеяния для Programming Exam Score vs Salary}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ programming\_exam\_score, }\AttributeTok{y =}\NormalTok{ salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"green"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Результат экзамена по программированию vs Зарплата"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Результат экзамена по программированию"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/program exam vs salary dist-1.pdf}

Корреляция между программированием и зарплатой

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Вычисление корреляции между Programming Exam Score и Salary}
\NormalTok{prog\_salary\_corr }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{programming\_exam\_score, salary\_data}\SpecialCharTok{$}\NormalTok{salary, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}

\CommentTok{\# Вывод результата}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation between Programming exam score and Salary:"}\NormalTok{, prog\_salary\_corr, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation between Programming exam score and Salary: -0.01988079
\end{verbatim}

\paragraph{\texorpdfstring{Наблюдения \texttt{Programming\ Exam\ Score}
vs.~\texttt{Salary}:}{Наблюдения Programming Exam Score vs.~Salary:}}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-programming-exam-score-vs.-salary}

Аналогично, диаграмма рассеяния для результатов экзамена по
программированию также не демонстрирует чёткой связи с зарплатой.
Коэффициент корреляции равен -0.02, что подтверждает слабую или
отсутствующую зависимость.

\subsubsection{Выводы:}\label{ux432ux44bux432ux43eux434ux44b}

Ни результаты экзаменов по математике, ни по программированию не
оказывают значимого влияния на зарплату. На уровень зарплаты, вероятно,
больше влияют такие факторы, как опыт работы, образование и должность.

\subsection{10.4 Связь между результатами экзаменов по математике и
программированию}\label{ux441ux432ux44fux437ux44c-ux43cux435ux436ux434ux443-ux440ux435ux437ux443ux43bux44cux442ux430ux442ux430ux43cux438-ux44dux43aux437ux430ux43cux435ux43dux43eux432-ux43fux43e-ux43cux430ux442ux435ux43cux430ux442ux438ux43aux435-ux438-ux43fux440ux43eux433ux440ux430ux43cux43cux438ux440ux43eux432ux430ux43dux438ux44e}

Мы проверим, существует ли связь между результатами экзаменов по
математике (\texttt{math\_exam\_score}) и программированию
(\texttt{programming\_exam\_score}) с помощью диаграммы рассеяния и
корреляции.

Построение диаграммы рассеяния

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Диаграмма рассеяния для Math Exam Score vs Programming Exam Score}
\FunctionTok{ggplot}\NormalTok{(salary\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ math\_exam\_score, }\AttributeTok{y =}\NormalTok{ programming\_exam\_score)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"purple"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Результат экзамена по математике vs экзамена по программированию"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Результат экзамена по математике"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Результат экзамена по программированию"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/math vs program dist-1.pdf}

Вычисление корреляции

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Вычисление корреляции между Math Exam Score и Programming Exam Score}
\NormalTok{math\_prog\_corr }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(salary\_data}\SpecialCharTok{$}\NormalTok{math\_exam\_score, salary\_data}\SpecialCharTok{$}\NormalTok{programming\_exam\_score, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}

\CommentTok{\# Вывод результата}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation between Math and Programming exam scores:"}\NormalTok{, math\_prog\_corr, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation between Math and Programming exam scores: 0.8208338
\end{verbatim}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-11}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Диаграмма рассеяния: Точки на графике демонстрируют чёткую
  положительную зависимость между результатами экзаменов по математике и
  программированию. Большинство точек лежат вдоль диагональной линии,
  что подтверждает высокую корреляцию между двумя переменными.
\item
  Корреляция: Коэффициент корреляции, составляет 0.82, что указывает на
  сильную положительную связь. Это подтверждает, что навыки, необходимые
  для экзаменов по математике и программированию, тесно связаны.
\item
  Выводы: Люди с высокими баллами по математике, как правило, показывают
  аналогично высокие результаты по программированию. Низкие баллы по
  математике также часто сопровождаются низкими баллами по
  программированию. Это может свидетельствовать о том, что базовые
  навыки, такие как аналитическое мышление или логика, одинаково важны
  для обоих экзаменов.
\end{enumerate}

\subsection{10.5 Влияет ли уровень образования на опыт
работы?}\label{ux432ux43bux438ux44fux435ux442-ux43bux438-ux443ux440ux43eux432ux435ux43dux44c-ux43eux431ux440ux430ux437ux43eux432ux430ux43dux438ux44f-ux43dux430-ux43eux43fux44bux442-ux440ux430ux431ux43eux442ux44b}

Мы исследуем связь между уровнем образования (\texttt{education\_level})
и средним опытом работы (\texttt{years\_of\_experience}), вычислим
средние значения и визуализируем их.

Средний опыт работы по уровням образования

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Группировка по уровню образования и расчёт среднего опыта работы}
\NormalTok{education\_experience }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(education\_level) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_years\_experience =} \FunctionTok{mean}\NormalTok{(years\_of\_experience, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}

\CommentTok{\# Вывод результатов}
\NormalTok{education\_experience}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 2
##   education_level avg_years_experience
##   <chr>                          <dbl>
## 1 Bachelor's                      5.42
## 2 High School                     1.92
## 3 Master's                        9.65
## 4 PhD                            13.9
\end{verbatim}

Визуализация: Столбчатая диаграмма

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение столбчатой диаграммы}
\FunctionTok{ggplot}\NormalTok{(education\_experience, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education\_level, }\AttributeTok{y =}\NormalTok{ avg\_years\_experience)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"orange"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Средний опыт работы по уровню образования"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Уровень образования"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Средний опыт работы (лет)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/edu vs exp bar-1.pdf}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-12}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Положительная связь между образованием и опытом: Люди с более высоким
  уровнем образования, такими как \texttt{PhD} и
  \texttt{Master\textquotesingle{}s}, имеют больше среднего опыта
  работы. \texttt{PhD} демонстрирует наибольший средний опыт работы,
  превышающий 13 лет.
\item
  Бакалавриат (\texttt{Bachelor\textquotesingle{}s}): Уровень Bachelor's
  имеет средний опыт около 5--6 лет, что меньше, чем у тех, кто завершил
  магистратуру или докторантуру.
\item
  Средняя школа (\texttt{High\ School}): Люди с уровнем High School
  имеют самый низкий средний опыт работы, около 2 лет. Это может быть
  связано с тем, что эти люди рано выходят на рынок труда и, возможно,
  имеют меньше возможностей для карьерного роста по сравнению с
  обладателями высших степеней.
\end{enumerate}

\paragraph{Выводы}\label{ux432ux44bux432ux43eux434ux44b-1}

Более высокие уровни образования требуют больше времени на обучение, что
часто означает, что люди старше и имели больше времени для накопления
опыта. Дополнительно, продвинутые ступени образования могут открывать
доступ к более длительной и стабильной занятости.

\subsection{10.6 Различия в зарплатах в зависимости от уровня
образования и
должности}\label{ux440ux430ux437ux43bux438ux447ux438ux44f-ux432-ux437ux430ux440ux43fux43bux430ux442ux430ux445-ux432-ux437ux430ux432ux438ux441ux438ux43cux43eux441ux442ux438-ux43eux442-ux443ux440ux43eux432ux43dux44f-ux43eux431ux440ux430ux437ux43eux432ux430ux43dux438ux44f-ux438-ux434ux43eux43bux436ux43dux43eux441ux442ux438}

Мы исследуем, существуют ли различия в средней зарплате в зависимости от
комбинации уровня образования (\texttt{education\_level}) и должности
(\texttt{job\_title}).

Средняя зарплата по уровням образования и должностям

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Группировка по job\_title и education\_level и расчёт средней зарплаты}
\NormalTok{job\_education\_salary }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(job\_title, education\_level) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_salary =} \FunctionTok{mean}\NormalTok{(salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ education\_level, }\AttributeTok{values\_from =}\NormalTok{ avg\_salary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'job_title'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Просмотр результата}
\NormalTok{job\_education\_salary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 191 x 5
## # Groups:   job_title [191]
##    job_title                     `Bachelor's` `High School` `Master's`    PhD
##    <chr>                                <dbl>         <dbl>      <dbl>  <dbl>
##  1 Account Manager                     75000            NA         NA      NA
##  2 Accountant                          55000            NA         NA      NA
##  3 Administrative Assistant            50000            NA         NA      NA
##  4 Back end Developer                  98744.        74264.    113598.     NA
##  5 Business Analyst                    75000            NA      80000      NA
##  6 Business Development Manager           NA            NA      90000      NA
##  7 Business Intelligence Analyst          NA            NA      85000      NA
##  8 CEO                                250000            NA         NA      NA
##  9 Chief Data Officer                     NA            NA         NA  220000
## 10 Chief Technology Officer               NA            NA         NA  250000
## # i 181 more rows
\end{verbatim}

Визуализация: Тепловая карта

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Установка пакета для тепловых карт (если не установлен)}
\CommentTok{\# install.packages("reshape2")}

\FunctionTok{library}\NormalTok{(reshape2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'reshape2'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:tidyr':
## 
##     smiths
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Преобразование данных для визуализации}
\NormalTok{job\_education\_salary\_long }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(}\FunctionTok{as.data.frame}\NormalTok{(job\_education\_salary), }\AttributeTok{id.vars =} \StringTok{"job\_title"}\NormalTok{, }\AttributeTok{variable.name =} \StringTok{"education\_level"}\NormalTok{, }\AttributeTok{value.name =} \StringTok{"avg\_salary"}\NormalTok{)}

\CommentTok{\# Построение тепловой карты}
\FunctionTok{ggplot}\NormalTok{(job\_education\_salary\_long, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education\_level, }\AttributeTok{y =}\NormalTok{ job\_title, }\AttributeTok{fill =}\NormalTok{ avg\_salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"white"}\NormalTok{, }\AttributeTok{high =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{na.value =} \StringTok{"grey"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Средняя зарплата по уровню образования и должности"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Уровень образования"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Должность"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Средняя зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/edu vs title heatmap-1.pdf}

Очень сложно воспринимать такой график, попробуем его немного настроить:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Фильтрация для топ{-}10 должностей с самой высокой средней зарплатой}
\NormalTok{top\_jobs }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(job\_title) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_salary =} \FunctionTok{mean}\NormalTok{(salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(avg\_salary)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{10}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pull}\NormalTok{(job\_title)}

\CommentTok{\# Отбор данных только для топ{-}10 должностей}
\NormalTok{filtered\_job\_education\_salary }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(job\_title }\SpecialCharTok{\%in\%}\NormalTok{ top\_jobs) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(job\_title, education\_level) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_salary =} \FunctionTok{mean}\NormalTok{(salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ education\_level, }\AttributeTok{values\_from =}\NormalTok{ avg\_salary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'job_title'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Преобразование данных в формат для тепловой карты}
\NormalTok{filtered\_job\_education\_salary\_long }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(}\FunctionTok{as.data.frame}\NormalTok{(filtered\_job\_education\_salary), }\AttributeTok{id.vars =} \StringTok{"job\_title"}\NormalTok{, }\AttributeTok{variable.name =} \StringTok{"education\_level"}\NormalTok{, }\AttributeTok{value.name =} \StringTok{"avg\_salary"}\NormalTok{)}

\CommentTok{\# Построение обновлённой тепловой карты}
\FunctionTok{ggplot}\NormalTok{(filtered\_job\_education\_salary\_long, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education\_level, }\AttributeTok{y =}\NormalTok{ job\_title, }\AttributeTok{fill =}\NormalTok{ avg\_salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"white"}\NormalTok{, }\AttributeTok{high =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{na.value =} \StringTok{"grey"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Средняя зарплата (топ{-}10 должностей)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Уровень образования"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Должность"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Средняя зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/edu vs title heatmap 2-1.pdf}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-13}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Связь между уровнем образования и зарплатой}:

  \begin{itemize}
  \tightlist
  \item
    У \texttt{CEO}, неожиданно, самая высокая средняя зарплата связана с
    уровнем образования \texttt{Bachelor\textquotesingle{}s}, а не с
    \texttt{PhD} или \texttt{Master\textquotesingle{}s}. Это может быть
    вызвано специфическими характеристиками выборки или уникальными
    карьерными траекториями.
  \item
    Для таких должностей, как \texttt{Chief\ Technology\ Officer} и
    \texttt{Chief\ Data\ Officer}, степень \texttt{PhD} явно связана с
    более высокими зарплатами.
  \end{itemize}
\item
  \textbf{Исключения}:

  \begin{itemize}
  \tightlist
  \item
    Должности, такие как \texttt{VP\ of\ Operations} и
    \texttt{VP\ of\ Finance}, демонстрируют слабую зависимость зарплаты
    от уровня образования. Возможно, на этих ролях большее значение
    имеют навыки управления и опыт.
  \end{itemize}
\item
  \textbf{Выделяющиеся роли}:

  \begin{itemize}
  \tightlist
  \item
    У \texttt{Chief\ Technology\ Officer} и
    \texttt{Chief\ Data\ Officer} степень \texttt{PhD} даёт значительное
    преимущество в зарплате.
  \item
    Напротив, для ролей \texttt{Director} и \texttt{Marketing\ Director}
    влияние образования на зарплату минимально.
  \end{itemize}
\item
  \textbf{Выводы}:

  \begin{itemize}
  \tightlist
  \item
    Хотя в большинстве случаев высшее образование приводит к более
    высоким зарплатам, есть исключения, такие как \texttt{CEO}, где
    фактор образования играет меньшую роль, и, возможно, большее влияние
    оказывают лидерские качества и опыт.
  \end{itemize}
\end{enumerate}

\section{11. Сводные
таблицы}\label{ux441ux432ux43eux434ux43dux44bux435-ux442ux430ux431ux43bux438ux446ux44b}

\subsection{11.1 Гендер vs Уровень образования -- Анализ
зарплат}\label{ux433ux435ux43dux434ux435ux440-vs-ux443ux440ux43eux432ux435ux43dux44c-ux43eux431ux440ux430ux437ux43eux432ux430ux43dux438ux44f-ux430ux43dux430ux43bux438ux437-ux437ux430ux440ux43fux43bux430ux442}

Мы создадим сводную таблицу для анализа зависимости средней зарплаты от
пола (\texttt{gender}) и уровня образования (\texttt{education\_level}),
а также визуализируем данные с помощью тепловой карты.

Сводная таблица: Средняя зарплата по полу и уровню образования

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Создание сводной таблицы}
\NormalTok{gender\_education\_pivot }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(gender, education\_level) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_salary =} \FunctionTok{mean}\NormalTok{(salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ education\_level, }\AttributeTok{values\_from =}\NormalTok{ avg\_salary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'gender'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Просмотр результата}
\NormalTok{gender\_education\_pivot}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 5
## # Groups:   gender [3]
##   gender `Bachelor's` `High School` `Master's`     PhD
##   <chr>         <dbl>         <dbl>      <dbl>   <dbl>
## 1 Female       89165.        30756.    122695. 160266.
## 2 Male         98972.        39381.    140061. 168711.
## 3 Other           NA        119949.    161393      NA
\end{verbatim}

Визуализация: Тепловая карта

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Преобразование данных в формат для тепловой карты}
\NormalTok{gender\_education\_long }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(}\FunctionTok{as.data.frame}\NormalTok{(gender\_education\_pivot), }\AttributeTok{id.vars =} \StringTok{"gender"}\NormalTok{, }\AttributeTok{variable.name =} \StringTok{"education\_level"}\NormalTok{, }\AttributeTok{value.name =} \StringTok{"avg\_salary"}\NormalTok{)}

\CommentTok{\# Построение тепловой карты}
\FunctionTok{ggplot}\NormalTok{(gender\_education\_long, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education\_level, }\AttributeTok{y =}\NormalTok{ gender, }\AttributeTok{fill =}\NormalTok{ avg\_salary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"white"}\NormalTok{, }\AttributeTok{high =} \StringTok{"red"}\NormalTok{, }\AttributeTok{na.value =} \StringTok{"grey"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Средняя зарплата по полу и уровню образования"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Уровень образования"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Пол"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Средняя зарплата"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/gender vs edu heatmap-1.pdf}

\subsubsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-14}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Увеличение зарплаты с уровнем образования: Зарплата возрастает с
  ростом уровня образования для всех категорий пола. Обладатели степени
  \texttt{PhD} получают самые высокие зарплаты, независимо от пола.
\item
  Гендерные различия: Мужчины (\texttt{Male}) получают более высокую
  среднюю зарплату по сравнению с женщинами (\texttt{Female}) на всех
  уровнях образования, особенно заметно на уровнях
  \texttt{Master\textquotesingle{}s} и \texttt{PhD}. Категория Other
  имеет меньше данных (серые ячейки), что ограничивает возможности
  анализа.
\item
  Самая высокая зарплата: PhD среди мужчин показывает наибольшую среднюю
  зарплату, превышающую 160,000.
\item
  Зависимость от уровня образования: Для женщин и мужчин зарплаты
  стабильно увеличиваются от \texttt{High\ School} к \texttt{PhD},
  подчёркивая значимость образования.
\end{enumerate}

Гендерный разрыв в зарплатах присутствует, но его выраженность зависит
от уровня образования. Например, разрыв становится особенно заметным на
уровне \texttt{Master\textquotesingle{}s} и \texttt{PhD}.

\section{11.2 Сводная таблица для опыта и зарплаты по уровню
образования}\label{ux441ux432ux43eux434ux43dux430ux44f-ux442ux430ux431ux43bux438ux446ux430-ux434ux43bux44f-ux43eux43fux44bux442ux430-ux438-ux437ux430ux440ux43fux43bux430ux442ux44b-ux43fux43e-ux443ux440ux43eux432ux43dux44e-ux43eux431ux440ux430ux437ux43eux432ux430ux43dux438ux44f}

Мы создадим сводную таблицу, чтобы проанализировать средние значения
опыта работы (\texttt{years\_of\_experience}) и зарплаты
(\texttt{salary}) по уровням образования (\texttt{education\_level}).

Сводная таблица: Опыт и зарплата по уровням образования

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Группировка по уровню образования и расчёт среднего опыта и зарплаты}
\NormalTok{experience\_salary\_pivot }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(education\_level) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{avg\_years\_experience =} \FunctionTok{mean}\NormalTok{(years\_of\_experience, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{avg\_salary =} \FunctionTok{mean}\NormalTok{(salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  )}

\CommentTok{\# Просмотр результата}
\NormalTok{experience\_salary\_pivot}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 3
##   education_level avg_years_experience avg_salary
##   <chr>                          <dbl>      <dbl>
## 1 Bachelor's                      5.42     95083.
## 2 High School                     1.92     36707.
## 3 Master's                        9.65    130112.
## 4 PhD                            13.9     165651.
\end{verbatim}

\subsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-15}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Связь между уровнем образования и опытом работы: Обладатели степени
  \texttt{PhD} имеют самый высокий средний опыт работы (13.9 лет), что
  значительно больше, чем у других уровней образования.
  \texttt{Master\textquotesingle{}s} также демонстрирует высокий средний
  опыт (9.65 лет), что почти в два раза больше, чем у тех, кто окончил
  только Bachelor's (5.42 года). Выпускники \texttt{High\ School} имеют
  самый низкий средний опыт работы (1.92 года), что может быть связано с
  более ранним выходом на рынок труда.
\item
  Связь между уровнем образования и зарплатой: Зарплата стабильно
  возрастает с ростом уровня образования: Выпускники
  \texttt{High\ School} имеют самую низкую среднюю зарплату (36,707).
  \texttt{Bachelor\textquotesingle{}s} повышает среднюю зарплату почти в
  3 раза по сравнению с \texttt{High\ School} (95,083).
  \texttt{Master\textquotesingle{}s} и \texttt{PhD} показывают самые
  высокие зарплаты --- 130,112 и 165,651, соответственно.
\item
  Выводы: Более высокий уровень образования связан как с большим
  количеством лет профессионального опыта, так и с более высоким уровнем
  дохода. Это подтверждает, что инвестиции в высшее образование приводят
  к долгосрочным преимуществам для карьеры и дохода. Здесь хорошое место
  для рекламной интеграции HSE.
\end{enumerate}

\section{11.3 Зарплаты после 10 лет
опыта}\label{ux437ux430ux440ux43fux43bux430ux442ux44b-ux43fux43eux441ux43bux435-10-ux43bux435ux442-ux43eux43fux44bux442ux430}

Мы сравним зарплаты \texttt{Data\ Scientist} с уровнями образования
\texttt{Bachelor\textquotesingle{}s} и \texttt{PhD}, которые имеют как
минимум 10 лет опыта работы. Также проверим различия между мужчинами и
женщинами в этих категориях.

Фильтрация данных

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Фильтрация данных: только Data Scientists с уровнями образования Bachelor\textquotesingle{}s и PhD, имеющие как минимум 10 лет опыта}
\NormalTok{filtered\_data }\OtherTok{\textless{}{-}}\NormalTok{ salary\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
\NormalTok{    job\_title }\SpecialCharTok{==} \StringTok{"Data Scientist"}\NormalTok{,}
\NormalTok{    education\_level }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Bachelor\textquotesingle{}s"}\NormalTok{, }\StringTok{"PhD"}\NormalTok{),}
\NormalTok{    years\_of\_experience }\SpecialCharTok{\textgreater{}=} \DecValTok{10}
\NormalTok{  )}

\CommentTok{\# Группировка по уровню образования и полу, расчёт средней зарплаты}
\NormalTok{salary\_comparison }\OtherTok{\textless{}{-}}\NormalTok{ filtered\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(education\_level, gender) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_salary =} \FunctionTok{mean}\NormalTok{(salary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ gender, }\AttributeTok{values\_from =}\NormalTok{ avg\_salary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'education_level'. You can override using
## the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Просмотр результата}
\NormalTok{salary\_comparison}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
## # Groups:   education_level [2]
##   education_level    Male Female
##   <chr>             <dbl>  <dbl>
## 1 Bachelor's      150000      NA
## 2 PhD             174607. 186000
\end{verbatim}

Визуализация: Сравнение зарплат

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Построение столбчатой диаграммы для сравнения зарплат}
\FunctionTok{ggplot}\NormalTok{(filtered\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education\_level, }\AttributeTok{y =}\NormalTok{ salary, }\AttributeTok{fill =}\NormalTok{ gender)) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"bar"}\NormalTok{, }\AttributeTok{position =} \FunctionTok{position\_dodge}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.8}\NormalTok{), }\AttributeTok{width =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Сравнение зарплат Data Scientist с уровнями образования Bachelor\textquotesingle{}s и PhD (10+ лет опыта)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Уровень образования"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Средняя зарплата"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Пол"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{0}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_files/figure-latex/data scientist plot-1.pdf}

\subsection{Наблюдения:}\label{ux43dux430ux431ux43bux44eux434ux435ux43dux438ux44f-16}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Сравнение зарплат между уровнями образования: Обладатели степени
  \texttt{PhD} стабильно зарабатывают больше, чем те, кто имеет степень
  \texttt{Bachelor\textquotesingle{}s}. Это подчёркивает значимость
  высшего уровня образования для высокооплачиваемых позиций, таких как
  Data Scientist.
\item
  Гендерные различия для PhD: Среди обладателей степени \texttt{PhD},
  женщины показывают чуть более высокую среднюю зарплату по сравнению с
  мужчинами. Это может быть связано с наличием меньшего количества
  данных, что приводит к преобладанию высоких зарплат в выборке женщин.
\item
  Отсутствие женщин в категории \texttt{Bachelor\textquotesingle{}s}: В
  данных отсутствуют женщины с уровнем образования
  \texttt{Bachelor\textquotesingle{}s} и более чем 10-летним опытом
  работы. Это ограничивает возможности анализа для этой категории.
\item
  Выводы: Уровень \texttt{PhD} обеспечивает значительное увеличение
  средней зарплаты, независимо от пола. Гендерные различия в категории
  \texttt{PhD} минимальны, что может говорить о более равномерной оплате
  труда на этом уровне образования.
\end{enumerate}

\section{Основные
выводы}\label{ux43eux441ux43dux43eux432ux43dux44bux435-ux432ux44bux432ux43eux434ux44b}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Гендерный разрыв: Мужчины чаще зарабатывают больше женщин на
  одинаковых позициях и уровнях образования, но в некоторых категориях,
  как \texttt{PhD}, разница минимальна или отсутствует.
\item
  Образование: Высшее образование (особенно \texttt{PhD} и
  \texttt{Master\textquotesingle{}s}) = выше зарплата. Но для некоторых
  ролей (\texttt{Software\ Engineer}) степень
  \texttt{Bachelor\textquotesingle{}s} всё ещё конкурентоспособна.
\item
  Опыт работы: Больше опыта = больше денег, но не всегда. Например, есть
  роли, где высокий доход доступен даже с меньшим опытом.
\item
  Экзамены: Результаты по математике и программированию почти не влияют
  на зарплату. Рынок ценит реальные навыки и опыт, а не академические
  баллы.
\end{enumerate}

\section{Итоги:}\label{ux438ux442ux43eux433ux438}

Высшее образование помогает, но не всегда определяет уровень дохода.
Гендерный разрыв всё ещё существует, особенно на высокооплачиваемых
должностях. Опыт и навыки остаются ключевыми для роста зарплаты.

\end{document}
